version: '2'


services:
  api:
    build:
      context: .
      dockerfile: DockerFile.api
    image: chatbot-api   
    ports:
      - "5000:5000"   
  client:
    build:
      context: .
      dockerfile: DockerFile.client
    image: chatbot
    depends_on:
      - api
    ports:
      - "81:80"
